[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/wishlist-bingo-app/*"
  to = "/wishlist-bingo-app/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/wishlist-bingo-app/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
